CUDA_DEVICE=/dev/nvidia/0
Wed May 14 20:51:55 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.239.06   Driver Version: 470.239.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:82:00.0 Off |                    0 |
| N/A   32C    P0    48W / 250W |      0MiB / 22919MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Module load: anaconda/3-2024.10-1
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/condabin/conda
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/bin/conda
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/bin/conda-env
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/bin/activate
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/bin/deactivate
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/etc/profile.d/conda.sh
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/etc/fish/conf.d/conda.fish
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/shell/condabin/Conda.psm1
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/shell/condabin/conda-hook.ps1
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /opt/modules/library/cpu/anaconda/3-2024.10-1/etc/profile.d/conda.csh
no change     /home/aaron.dichoso/.bashrc
No action taken.
/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 20 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/scratch1/aaron.dichoso
--------------------training----------------------
Traceback (most recent call last):
  File "/scratch1/aaron.dichoso/RISNet/Train.py", line 130, in <module>
    train(train_loader, model, optimizer, epoch, opt, total_step, writer)
  File "/scratch1/aaron.dichoso/RISNet/Train.py", line 36, in train
    for step, data in enumerate(train_loader):
  File "/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaron.dichoso/.conda/envs/RISNet/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/scratch1/aaron.dichoso/RISNet/utils/dataloader.py", line 113, in __getitem__
    depth = self.rgb_loader(self.depths[index])
                            ~~~~~~~~~~~^^^^^^^
IndexError: list index out of range

srun: error: saliksik-gpu-02: task 0: Exited with exit code 1
